//$Id: TPZPlasticStepID.h,v 1.3 2010-06-11 22:12:14 diogo Exp $

#ifndef TPZPLASTICSTEPID_H
#define TPZPLASTICSTEPID_H

const int TPZDRUCKERPRAGERPLASTICMODEL_ID   = 2;
const int TPZMOHRCOULOMBPLASTICMODEL_ID   = 3;
const int TPZMODIFIEDMOHRCOULOMBPLASTICMODEL_ID   = 4;
const int TPZWILLAMWARNKEPARENT_ID   = 5;
const int TPZVONMISES_ID = 6;



const int LADEKIMPLASTICMODEL_ID 			= 0;
const int SANDLERDIMAGGIOPLASTICMODEL_ID 	= 1;

const int BASEPLASTICMODEL_ID				= 399;

const int TPZLADEKIM_ID          			= BASEPLASTICMODEL_ID-LADEKIMPLASTICMODEL_ID;
const int TPZSANDLERDIMAGGIO_ID  			= BASEPLASTICMODEL_ID-SANDLERDIMAGGIOPLASTICMODEL_ID;
const int TPZDRUCKERPRAGER_ID          		= BASEPLASTICMODEL_ID-TPZDRUCKERPRAGERPLASTICMODEL_ID;
const int TPZMOHRCOULOMB_ID          		= BASEPLASTICMODEL_ID-TPZMOHRCOULOMBPLASTICMODEL_ID;
const int TPZMODIFIEDMOHRCOULOMB_ID          = BASEPLASTICMODEL_ID-TPZMODIFIEDMOHRCOULOMBPLASTICMODEL_ID;

const int LASTPLASTIC_ID = TPZSANDLERDIMAGGIO_ID;
//const int TPZMatElastoPlastic2D_ID;

#endif
