//
//  tpzgeomid.h
//  PZ
//
//  Created by Philippe Devloo on 3/21/14.
//
//

#ifndef PZ_tpzgeomid_h
#define PZ_tpzgeomid_h

const int TPZGEOELEMENTARC3DID = 350;
/// Id for three dimensional ellipse element
const int TPZGEOELEMENTELLIPSE3DID = 301;

///CreateGeoElement -> TPZQuadraticCube

const int TPZGEOELEMENTQUADRATICCUBEID = 3521;

const int TPZGEOELEMENTQUADRATICLINEID = 3111;

const int TPZGEOELEMENTQUADRATICPRISM = 3535;

const int TPZGEOELEMENTQUADRATICPYRAMIDID = 3522;

const int  TPZGEOELEMENTQUADRATICQUADID = 352;

const int  TPZGEOELEMENTQUADRATICTETRAID = 312;

const int TPZGEOELEMENTQUADRATICTRIANGLEID = 318;

const int TPZGEOELEMENTWAVYLINEID = 319;

const int TPZGEOELEMENTTRIANGLESPHEREID = 320;

const int TPZGEOELEMENTQUADSPHEREID = 321;

const int TPZGEOELEMENTQUADTORUSID = 322;

const int TPZGEOELEMENTTRIANGLETORUSID = 323;

const int TPZGEOELEMENTQUADSPHEREBLENDID = 324;

const int TPZGEOELEMENTTRIANGLESPHEREBLENDID = 325;


#endif
