// Generated by Together

/** @file pzmanvectorgen.cc */
// $Id: pzmanvectorgen.cc,v 1.1.1.1 2003-02-04 16:45:27 cantao Exp $

#include "pzmanvector.h"
#include "pzstring.h" 

template class TPZManVector< int >;
template class TPZManVector< long int >;
template class TPZManVector< int *>;
template class TPZManVector< char *>;
template class TPZManVector< REAL >;
template class TPZManVector< REAL * >;
template class TPZManVector<TPZString>;

//--| PZ |----------------------------------------------------------------------
