/* Generated by Together */

#ifndef TPZBLOCKDIAGONALSTRUCTMATRIX_H
#define TPZBLOCKDIAGONALSTRUCTMATRIX_H
#include "pzstrmatrix.h"
class TPZCompMesh;
class TPZFMatrix;
class TPZMatrix;
class TPZBlockDiagonal;
template <class T>
class TPZVec;

/**
 * Implements Block Diagonal Structural Matrices
 * @ingroup structural
 */
class TPZBlockDiagonalStructMatrix : public TPZStructMatrix {
public:    

  TPZBlockDiagonalStructMatrix(TPZCompMesh *);
  
  virtual TPZMatrix * Create();
  
  virtual TPZMatrix * CreateAssemble(TPZFMatrix &rhs);

  virtual TPZStructMatrix * Clone();    
  
  static int main();

public:

    void AssembleBlockDiagonal(TPZBlockDiagonal & block);
private:
    void BlockSizes(TPZVec < int > & blocksizes);
};
#endif //TPZBLOCKDIAGONALSTRUCTMATRIX_H
