/* Generated by Together */

#ifndef TPZBANDSTRUCTMATRIX_H
#define TPZBANDSTRUCTMATRIX_H
#include "pzstrmatrix.h"
class TPZCompMesh;
class TPZFMatrix;
class TPZMatrix;

/**
 * Implements Banded Structural Matrices
 * @ingroup structural
 */
class TPZBandStructMatrix : public TPZStructMatrix {
public:    

    TPZBandStructMatrix(TPZCompMesh *);
    
    ~TPZBandStructMatrix();

    TPZBandStructMatrix(const TPZBandStructMatrix &copy) : TPZStructMatrix(copy)
    {
    }

    virtual TPZMatrix * Create();

    virtual TPZMatrix * CreateAssemble(TPZFMatrix &rhs);

    virtual TPZStructMatrix * Clone();

public:
};
#endif //TPZBANDSTRUCTMATRIX_H
