/* Generated by Together */

#include "pzbstrmatrix.h"
#include "pzbndmat.h"
#include "pzcmesh.h"

TPZStructMatrix * TPZBandStructMatrix::Clone(){
    return new TPZBandStructMatrix(fMesh);
}
TPZMatrix * TPZBandStructMatrix::CreateAssemble(TPZFMatrix &rhs){
    int neq = fMesh->NEquations();
    int band = fMesh->BandWidth();
    TPZFBMatrix *stiff = new TPZFBMatrix(neq,band);
    rhs.Redim(neq,1);
    Assemble(*stiff,rhs);
    return stiff;
}
TPZMatrix * TPZBandStructMatrix::Create(){
    int neq = fMesh->NEquations();
    int band = fMesh->BandWidth();
    return new TPZFBMatrix(neq,band);
}
TPZBandStructMatrix::TPZBandStructMatrix(TPZCompMesh *mesh) : TPZStructMatrix(mesh)
{}
