/* Generated by Together */

#include "pzsbstrmatrix.h"

#include "pzsbndmat.h"
#include "pzcmesh.h"

TPZStructMatrix * TPZSBandStructMatrix::Clone(){
    return new TPZSBandStructMatrix(fMesh);
}
TPZMatrix * TPZSBandStructMatrix::CreateAssemble(TPZFMatrix &rhs){
    int neq = fMesh->NEquations();
    int band = fMesh->BandWidth();
    TPZSBMatrix *stiff = new TPZSBMatrix(neq,band);
    rhs.Redim(neq,1);
    Assemble(*stiff,rhs);
    return stiff;
}
TPZMatrix * TPZSBandStructMatrix::Create(){
    int neq = fMesh->NEquations();
    int band = fMesh->BandWidth();
    return new TPZSBMatrix(neq,band);
}
TPZSBandStructMatrix::TPZSBandStructMatrix(TPZCompMesh *mesh) : TPZStructMatrix(mesh)
{}
