/* Generated by Together */

#include "pzskylstrmatrix.h"
#include "pzskylmat.h"
#include "pzcmesh.h"
#include "pzvec.h"

TPZStructMatrix * TPZSkylineStructMatrix::Clone(){
    return new TPZSkylineStructMatrix(fMesh);
}
TPZMatrix * TPZSkylineStructMatrix::CreateAssemble(TPZFMatrix &rhs){
    int neq = fMesh->NEquations();
    TPZVec<int> skyline;
    fMesh->Skyline(skyline);
    TPZSkylMatrix *stiff = new TPZSkylMatrix(neq,skyline);
    rhs.Redim(neq,1);
    Assemble(*stiff,rhs);
    return stiff;
}
TPZMatrix * TPZSkylineStructMatrix::Create(){
    int neq = fMesh->NEquations();
    TPZVec<int> skyline;
    fMesh->Skyline(skyline);
    return new TPZSkylMatrix(neq,skyline);
}
TPZSkylineStructMatrix::TPZSkylineStructMatrix(TPZCompMesh *mesh) : TPZStructMatrix(mesh)
{}
