/* Generated by Together */

#ifndef TPZSKYLINESTRUCTMATRIX_H
#define TPZSKYLINESTRUCTMATRIX_H
#include "pzstrmatrix.h"
class TPZCompMesh;
class TPZFMatrix;
class TPZMatrix;

/**
 * Implements SkyLine Structural Matrices
 * ingroup structural
 */
class TPZSkylineStructMatrix : public TPZStructMatrix {
public:    

    TPZSkylineStructMatrix(TPZCompMesh *);

    virtual TPZMatrix * Create();

    virtual TPZMatrix * CreateAssemble(TPZFMatrix &rhs);

    virtual TPZStructMatrix * Clone();

public:
};
#endif //TPZSKYLINESTRUCTMATRIX_H
