ENABLE_TESTING()

#Running the executable and test if it will run ok
ADD_TEST (Cubo_do_Nathan Cubo_do_Nathan)

#Checking generated files
SET (filename "Cube.vtk")
SET (expectedMD5 "64aa9b689c442c5bf3b0a2b428fc0985")
add_test (Cubo_do_Nathan_Cube.vtk "${CMAKE_COMMAND}" "-Dfilename:STRING=${filename}" "-DexpectedMD5:STRING=${expectedMD5}" "-P" "${CMAKE_SOURCE_DIR}/Tests/MD5FileTest.cmake")
SET (filename "malhaPZ1BC.txt")
SET (expectedMD5 "fdc16e681800611f9730a5ffcf9d231b")
add_test (Cubo_do_Nathan_malhaPZ1BC.txt "${CMAKE_COMMAND}" "-Dfilename:STRING=${filename}" "-DexpectedMD5:STRING=${expectedMD5}" "-P" "${CMAKE_SOURCE_DIR}/Tests/MD5FileTest.cmake")
SET (filename "malha1.txt")
SET (expectedMD5 "4aaefc81181c6d201bd9d9c2a3b886d9")
add_test (Cubo_do_Nathan_malha1.txt "${CMAKE_COMMAND}" "-Dfilename:STRING=${filename}" "-DexpectedMD5:STRING=${expectedMD5}" "-P" "${CMAKE_SOURCE_DIR}/Tests/MD5FileTest.cmake")
SET (filename "malha2.txt")
SET (expectedMD5 "a54742a43118fad7e53e9dc949d6054e")
add_test (Cubo_do_Nathan_malha2.txt "${CMAKE_COMMAND}" "-Dfilename:STRING=${filename}" "-DexpectedMD5:STRING=${expectedMD5}" "-P" "${CMAKE_SOURCE_DIR}/Tests/MD5FileTest.cmake")
SET (filename "discont.scal_vec.0.vtk")
SET (expectedMD5 "a0c66b419438566faf2d9686a70f0491")
add_test (Cubo_do_Nathan_discont.scal_vec.0.vtk "${CMAKE_COMMAND}" "-Dfilename:STRING=${filename}" "-DexpectedMD5:STRING=${expectedMD5}" "-P" "${CMAKE_SOURCE_DIR}/Tests/MD5FileTest.cmake")
SET (filename "discont.scal_vec.1.vtk")
SET (expectedMD5 "55cda7ba61077d5319eb6f640314137e")
add_test (Cubo_do_Nathan_discont.scal_vec.1.vtk "${CMAKE_COMMAND}" "-Dfilename:STRING=${filename}" "-DexpectedMD5:STRING=${expectedMD5}" "-P" "${CMAKE_SOURCE_DIR}/Tests/MD5FileTest.cmake")
SET (filename "discont.scal_vec.2.vtk")
SET (expectedMD5 "65c8fc89e5fa5dfc2a36309197ba282b")
add_test (Cubo_do_Nathan_discont.scal_vec.2.vtk "${CMAKE_COMMAND}" "-Dfilename:STRING=${filename}" "-DexpectedMD5:STRING=${expectedMD5}" "-P" "${CMAKE_SOURCE_DIR}/Tests/MD5FileTest.cmake")
SET (filename "discont.scal_vec.3.vtk")
SET (expectedMD5 "4e7c124ffccf8da3ea7d77f652630374")
add_test (Cubo_do_Nathan_discont.scal_vec.3.vtk "${CMAKE_COMMAND}" "-Dfilename:STRING=${filename}" "-DexpectedMD5:STRING=${expectedMD5}" "-P" "${CMAKE_SOURCE_DIR}/Tests/MD5FileTest.cmake")
SET (filename "discont.scal_vec.4.vtk")
SET (expectedMD5 "e64b10cd91282d46b57f74b790693b81")
add_test (Cubo_do_Nathan_discont.scal_vec.4.vtk "${CMAKE_COMMAND}" "-Dfilename:STRING=${filename}" "-DexpectedMD5:STRING=${expectedMD5}" "-P" "${CMAKE_SOURCE_DIR}/Tests/MD5FileTest.cmake")
SET (filename "discont.scal_vec.5.vtk")
SET (expectedMD5 "ea7d4adde4e80ae1a8d5591787d07a03")
add_test (Cubo_do_Nathan_discont.scal_vec.5.vtk "${CMAKE_COMMAND}" "-Dfilename:STRING=${filename}" "-DexpectedMD5:STRING=${expectedMD5}" "-P" "${CMAKE_SOURCE_DIR}/Tests/MD5FileTest.cmake")


#Adding dependency
#set_tests_properties (VisualMatrix_visualmatrix.dx PROPERTIES DEPENDS "VisualMatrix" REQUIRED_FILES "${filename}")
