//DO NOT COMMIT THIS FILE, LOCAL USE ONLY

//DO NOT COMMIT THIS FILE, LOCAL USE ONLY

//DO NOT COMMIT THIS FILE, LOCAL USE ONLY

//DO NOT COMMIT THIS FILE, LOCAL USE ONLY

#ifndef REALdouble
#define REALdouble
#endif
#ifndef STATEdouble
#define STATEdouble
#endif