/**
 * This classroom extends a dimension mesh n = 1,2 
 * for a dimension mesh n+1 = 2,3 respectively, 
 * the entrance data are the fine mesh and the thickness of the new mesh
 * restrictions:
 * - for now the mesh it must be plain
 * - the nodes of the mesh must be given with three co-ordinated
 */

#ifndef TPZEXTENDGRID_HPP
#define TPZEXTENDGRID_HPP

class TPZGeoMesh;
using namespace std;
#include "pzstack.h"
#include <fstream>

/*************/

/// class which generates a three dimensional mesh as an extension of a two dimensional mesh
class TPZExtendGridDimension {

  /**
   * thickness of the mesh (+  or -)
   */
  REAL fThickness;

  /**
   * name of the fine mesh to be extended
   */
  ifstream fFineFileMesh;

  /**
   * fine geometric mesh generated by the NeoPZ
   */
  TPZGeoMesh *fFineGeoMesh;

 public:
  
  TPZExtendGridDimension(char *geofile,REAL thickness);
  TPZExtendGridDimension(TPZGeoMesh *finegeomesh,REAL thickness);
  
  ~TPZExtendGridDimension(){};

  /*
   * it reads the mesh since the archive of entrance finemesh,
   * passed in the constructor, and returns extended mesh
   */
  TPZGeoMesh *ExtendedMesh();

  /*
   * it prints the generated mesh
   */
  void PrintGeneratedMesh(ostream &out = cout);
  
};

#endif
