Darcy flow
----------

.. toctree::
   :maxdepth: 1

.. contents:: Table of Contents
   :local:

Materials for solving the Darcy flow equation:

.. math::

   \nabla \cdot \boldsymbol{\sigma} = f

   \boldsymbol{\sigma} = - K \nabla u


TPZDarcyFlow
^^^^^^^^^^^^

.. doxygenclass:: TPZDarcyFlow
   :members:

TPZMixedDarcyFlow
^^^^^^^^^^^^^^^^^

.. doxygenclass:: TPZMixedDarcyFlow
   :members:

TPZIsotropicPermeability
^^^^^^^^^^^^^^^^^^^^^^^^

.. doxygenclass:: TPZIsotropicPermeability
   :members:
