function(check_pz_opt opt res)
  if(CMAKE_IS_PZ_BUILDTREE)
    string(COMPARE EQUAL "${${opt}}" "ON" result)
    if(NOT result)
      string(REGEX REPLACE "^PZ_" "" opt ${opt})
      string(COMPARE EQUAL "${${opt}}" "ON" result)
    endif()
  else()
    get_property(result GLOBAL PROPERTY ${opt})
  endif()
  set(${res} ${result} PARENT_SCOPE)
endfunction()