function(enable_likwid target)
    find_path(LIKWID_INCLUDE likwid.h PATHS ${SEARCH_DIRS})
    find_library(LIKWID_LIB NAMES liblikwid.a PATHS ${SEARCH_DIRS})
    if(LIKWID_INCLUDE-NOTFOUND)
        set (LIKWID_INCLUDE "" CACHE PATH "Directory where likwid header files can be found")
    else()
        include_directories(${LIKWID_INCLUDE})
    endif()
    if(LIKWID_LIB-NOTFOUND)
        set (LIKWID_LIB "" CACHE PATH "Directory where the likwid library can be found")
    else()
        target_link_libraries(${target} PRIVATE ${LIKWID_LIB})
    endif()
endfunction()
