function(enable_metis target)
  find_package(METIS REQUIRED)
  target_link_libraries(${target} PRIVATE ${METIS_LIBRARIES})
  target_include_directories(${target} PRIVATE ${METIS_INCLUDE_DIRS})
endfunction()
