function(enable_hwloc target)
    find_path(HWLOC_INCLUDE NAMES hwloc.h PATHS ${SEARCH_DIRS})
    find_library(HWLOC_LIB NAMES hwloc.a libhwloc.so libhwloc.dylib PATHS ${SEARCH_DIRS})
    if(HWLOC_INCLUDE-NOTFOUND)
        set (HWLOC_INCLUDE "" CACHE PATH "Directory where hwloc.h can be found")
    endif()
    if(HWLOC_LIB-NOTFOUND)
        set (HWLOC_LIB "" CACHE PATH "Directory where the hwloc library can be found")
    endif()
    target_link_libraries(${target} PRIVATE ${HWLOC_LIB})
endfunction()