function(enable_boost target)
    if (NOT "$ENV{BOOST_ROOT}" STREQUAL "")
        message(STATUS "Looking for boost in $ENV{BOOST_ROOT}")
    endif()
    find_package( Boost COMPONENTS graph date_time  REQUIRED )
    target_link_libraries(${target} PRIVATE Boost::date_time Boost::graph)
    target_include_directories(${target} PRIVATE ${Boost_INCLUDE_DIRS})
    target_compile_definitions(${target} PRIVATE USING_BOOST)
    target_compile_definitions(${target} INTERFACE PZ_USING_BOOST)
    mark_as_advanced(Boost_GRAPH_LIBRARY_RELEASE  Boost_DATE_TIME_LIBRARY_RELEASE  Boost_INCLUDE_DIRS Boost_INCLUDE_DIR)
endfunction()
