function(enable_metis target)
  if(USING_MUMPS AND MUMPS_metis)
    message(STATUS "[NeoPZ] MUMPS already configured with METIS support, skipping separate METIS setup")
  else()
    find_package(METIS REQUIRED)
  endif()
  target_link_libraries(${target} PRIVATE ${METIS_LIBRARIES})
  target_include_directories(${target} PRIVATE ${METIS_INCLUDE_DIRS})
  target_compile_definitions(${target} PRIVATE PZ_USING_METIS)
  target_compile_definitions(${target} INTERFACE PZ_USING_METIS)
endfunction()
