function(enable_papi target)
    find_path(PAPI_INCLUDE NAMES papi.h PATHS ${SEARCH_DIRS})
    find_library(PAPI_LIB NAMES libpapi.a libpapi.so PATHS ${SEARCH_DIRS})
    if(PAPI_INCLUDE-NOTFOUND)
        set (PAPI_INCLUDE "" CACHE PATH "Directory where papi.h can be found")
    endif()
    if(PAPI_LIB-NOTFOUND)
        set (PAPI_LIB "" CACHE PATH "Directory where the papi library can be found")
    endif()
    target_link_libraries(${target} PRIVATE ${PAPI_LIB})
endfunction()