function(enable_metis target)
    find_path(METIS_INCLUDE metis.h PATHS ${SEARCH_DIRS})
    find_library(METIS_LIB NAMES libmetis.dylib metis.lib libmetis.so libmetis.a PATHS ${SEARCH_DIRS})
    if(METIS_INCLUDE-NOTFOUND)
        set (METIS_INCLUDE "" CACHE PATH "Directory where metis header files can be found")
    else()
        include_directories(${METIS_INCLUDE})
    endif()
    if(METIS_LIB-NOTFOUND)
        set (METIS_LIB "" CACHE PATH "Directory where the metis library can be found")
    endif()
    target_link_libraries(${target} PRIVATE ${METIS_LIB})
    target_include_directories(${target} PRIVATE ${METIS_INCLUDE})
endfunction()
