function(enable_blaze target)
    if (NOT USING_MKL AND NOT USING_LAPACK)
        message(FATAL_ERROR "Blaze library requires either USING_MKL or USING_LAPACK enabled!")
    endif()
    find_package(blaze REQUIRED)
    if (blaze_FOUND)
        #link_libraries(${MKL_LIB_INTEL})
        add_library(blaze_target INTERFACE)
    else()
        set (USING_BLAZE "" CACHE PATH "Directory where blaze can be found")
    endif()
    target_compile_definitions(${target} PRIVATE USING_BLAZE)
    target_link_libraries(${target} PRIVATE blaze::blaze)
    # Blaze docs enforce this line. Mandatory under Windows. In future, should include "INTERFACE" modifier.
endfunction()