function(enable_numa target)
    find_path(LIBNUMA_INCLUDE numa.h PATHS ${SEARCH_DIRS})
    find_library(LIBNUMA_LIB NAMES libnuma.so PATHS ${SEARCH_DIRS})
    if(LIBNUMA_INCLUDE-NOTFOUND)
        set (LIBNUMA_INCLUDE "" CACHE PATH "Directory where libnuma header files can be found (consider installing libnuma-dev)")
    else()
        include_directories(${LIBNUMA_INCLUDE})
    endif()
    if(LIBNUMA_LIB-NOTFOUND)
        set (LIBNUMA_LIB "" CACHE PATH "Directory where the libnuma library can be found")
    else()
        target_link_libraries(${target} PRIVATE ${LIBNUMA_LIB})
    endif()
endfunction()