name: Run Unit Tests with MKL
on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [main, develop]

env:
  BUILD_TYPE: Release

jobs:
  Run_unit_tests_with_MKL:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/labmec/neopz-deps:latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: |
          cmake -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
            -DBUILD_UNITTESTING=ON \
            -DUSING_MKL=ON \
            -DMKL_ROOT=$MKLROOT \
            -DUSING_LOG4CXX=ON \
            -DUSING_METIS=ON \
            -DUSING_MUMPS=ON \
            -DMUMPS_ROOT=$MUMPS_ROOT \
            -DMUMPS_USE_DOUBLE=ON \
            -DMUMPS_USE_COMPLEX16=ON

      - name: Build
        run: cmake --build build
        env:
          MAKEFLAGS: "-j4"

      - name: Run Unit Tests
        run: ctest --test-dir build -C ${{ env.BUILD_TYPE }}
        env:
          CTEST_OUTPUT_ON_FAILURE: 1